projeto/routes/web.php
<?php

use App\Http\Controllers\apiController;
use App\Http\Controllers\collectionController;
use App\Http\Controllers\comicsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::resource('colecao', collectionController::class); //it call by itself all the defined seven method of the controller

Route::resource('colecao', collectionController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::controller(apiController::class)->group(function () {
    Route::get('/api/adicionarhq','add')->name('api.add');
    Route::post('/api/salvar','store')->name('api.store');
    Route::post('/api/busca','chamada')->name('api.chamada');
    Route::post('/api/retorno','retorno')->name('api.retorno');
});

Route::get('/colecao/{colecao}/comics', [comicsController::class, 'index'])->name('comics.index');
Route::post('/colecao/{colecao}/comics', [comicsController::class, 'readed'])->name('comics.readed');

Route::middleware(['auth:sanctum', config('jetstream.auth_session'),'verified'])->group(function () {
    Route::get('/colecao/colecao', function () {
        return view('colecao');
    })->name('colecao');
});

require_once __DIR__ . '/jetstream.php';
require_once __DIR__ . '/fortify.php';

projeto/resources/views/colecao/create.blade.php
<x-layout title="Nova Coleção">
    <div style="position: static">
        <a href="/colecao" class="btn btn-dark" style="position: absolute; left: 16%; top: 12%;">Voltar</a>
    </div>
    <x-colecao.form :action="route('colecao.store')" :nome="old('nome')" :update="false" />
</x-layout>

projeto/resources/views/colecao/destroy.blade.php
<x-layout title="Excluir Coleção">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <style>
        .botao-delete{
            margin-top: 13px;
            font-size: 20px;
        }
        li::marker{
            content: none;
        }
        .aviso-delete{
            font-size: 30px;
            color: red;
            font-weight: bold;
            margin-top: 5%;
            margin-bottom: 5%;
        }
        :disabled {
            background-color:#d9d9d9;
            color:black;
        }
        .input-text{
            text-align: center;
            padding: 0.375rem 0.75rem 0.375rem 0.75rem; font-size: 2.5rem;
            border-radius: 5px;
        }
        .box-input{
            margin-top: 5%;
        }

    </style>
    <a href="/colecao" class="btn btn-dark" style="position: absolute; right: 80%; top: 12%;">Voltar</a>

    <div class="box-input">
        <input type="text" class="input-text" value="{{ $colecao->name_collection }}" disabled>
    </div>
    <div class="aviso-delete">
        <span>
            Atenção: ação irreversível <br>
            Tem certeza que deseja excluir a coleção <br>
            inteira com todos os itens?
        </span>
    </div>
    <li>
        <form action="{{ route('colecao.destroy', $colecao->id) }}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger btn-md botao-delete">Excluir</button>
        </form>
    </li>
</x-layout>

projeto/resources/views/colecao/edit.blade.php
<x-layout title="Editar Coleção '{!! $colecao->name_collection !!}'">
    <a href="/colecao" class="btn btn-dark" style="position: absolute; right: 80%; top: 12%;">Voltar</a>
    <x-colecao.form :action="route('colecao.update', $colecao->id)" :nome="$colecao->name_collection" :update="true"/>
</x-layout>

projeto/resources/views/colecao/index.blade.php
<x-layout title="Suas coleções" :mensagem-sucesso="$mensagemSucesso">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <style>
        .containerColecao{
            width: 848px;
            margin: 20px auto;
        }
        .botaoCriar{
            box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.5);
            border-radius: 5px;
            font-size: 20px;
            margin-top: 3%;
        }
        .boxTitulos{
            border: 5px solid rgba(0, 0, 0, .025);
            font-size: 20px;
            background-color: #d9d9d9
        }
        .boxDadosColecao{
            border: 5px solid rgba(0, 0, 0, .125);
            font-size: 25px
        }
        .botaoDown {
            box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.5);
            border-radius: 5px;
        }
        .aviso-sem-colecao{
            margin-top: 10%;
        }
        .box-sem-colecao{
            position: absolute;
            width: 845px;
            height: 0px;
            left: 537px;
            top: 512px;
            border: 1px solid #000000;
        }
        .box-dados-colecao1{
            margin-left: -23px
        }
        .box-dados-colecao2{
            margin-left: 82px
        }
        .box-dados-colecao3{
            margin-right: 58px
        }
    </style>
        <a href="{{ route('colecao.create') }}" class="btn btn-info mb-3 botaoCriar">Criar Coleção</a>
    <ul class="list-group containerColecao">
        <li class="list-group-item d-flex justify-content-between align-items-center boxTitulos">
            <ul class="box-dados-colecao1">Id</ul> <ul class="box-dados-colecao2">Nome</ul> <ul class="box-dados-colecao3">Ações</ul>
        </li>

        @if(!empty($colecoesUsuario))
            @foreach($colecoes as $colecao)
                <li class="list-group-item d-flex justify-content-between align-items-center boxDadosColecao" style="">
                    <div>{{$colecao->id}}</div>

                    <div style="margin-right: -126px;">{{$colecao->name_collection}}</div>

                    <div class="btn-group botaoDown">
                        <button type="button" class="btn btn-primary">
                            <a href="{{ route('comics.index', $colecao->id) }}" style="color: white; text-decoration: none; font-size: 20px">Ver Coleção</a>
                        </button>
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ route('colecao.edit', $colecao->id) }} " class="btn btn-dark" style="font-size: 20px"> Editar Coleção </a>
                            </li>
                            <li>
                                <a href="{{ route('api.add', $colecao->id) }}" class="btn btn-info btn-md" style="margin-top: 13px; font-size: 20px"> Adicionar HQ </a>
                            </li>
                            @if($colecao->id)
                            <li style="margin-top: 11px;">
                                <a href="{{ route('colecao.show', $colecao->id) }} " class="btn btn-danger" style="font-size: 20px"> Remover Coleção </a>
                            </li>
                            @endif
                        </ul>
                    </div>
                </li>
            @endforeach
        @endif
            @empty($colecao)
                <div class="aviso-sem-colecao">
                    <p class="box-sem-colecao">Ainda não há coleções</p>
                </div>
            @endempty
    </ul>
</x-layout>